// THIS FILE IS AUTOGENERATED DO NOT EDIT BY HAND
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Drawing;
using Mutagen.Bethesda.Skyrim;
using Spriggan.Converters.Base;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Strings;
using Microsoft.Extensions.DependencyInjection;
using Mutagen.Bethesda.Plugins.Records;
using System.Globalization;
using Mutagen.Bethesda.Plugins;
using Noggog;

internal static class IBaseLayerGetter_Writer
{
    public static void WriteOuter(Utf8JsonWriter writer, Mutagen.Bethesda.Skyrim.IBaseLayerGetter? value, JsonSerializerOptions options)
    {
        if (value != null)
        {
            writer.WriteStartObject();
            switch (value)
            {
                case Mutagen.Bethesda.Skyrim.IAlphaLayerGetter itm1:
                    writer.WriteString("$type", "AlphaLayer");
                    AlphaLayer_Writer.WriteInner(writer, itm1, options);
                    break;
            }
            writer.WriteEndObject();
        }
        else
        {
            writer.WriteNullValue();
        }
    }
}
