using System.Reactive.Disposables;
using System.Reflection;
using System.Text.Json;
using Loqui;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Noggog;
using Spriggan.TupleGen;

namespace Spriggan.ConverterGenerators;

using System.IO;
using System.Text;

public class CFile
{
    private readonly StringBuilder _sb;
    private int _indent;


    private Dictionary<Type, Action<Type, string>> _writerEmitters;
    private Dictionary<Type, Action<Type, string>> _readerEmitters;
    private readonly GameRelease _game;
    private int genSym = 0;


    public CFile(GameRelease game)
    {
        _game = game;
        _writerEmitters = new()
        {
            {typeof(IFormLinkNullableGetter<>), IFormLinkNullableWriter},
            {typeof(IFormLinkGetter<>), IFormLinkWriter},
            {typeof(IReadOnlyList<>), IReadOnlyListWriter},
            {typeof(float), PrimitiveWriter<float>},
            {typeof(bool), PrimitiveWriter<bool>},
            {typeof(ILoquiObject), LoquiObjectWriter},
            {typeof(Enum), EnumWriter},
        };

        _readerEmitters = new()
        {
            {typeof(IFormLinkNullable<>), IFormLinkNullableReader},
            {typeof(ExtendedList<>), ExtendedListReader},
            {typeof(float), PrimitiveReader<float>},
            {typeof(bool), PrimitiveReader<bool>},
            {typeof(ILoquiObject), LoquiObjectReader},
            {typeof(Enum), EnumReader}

        };

        
        _sb = new StringBuilder();
        Code("// THIS FILE IS AUTOGENERATED DO NOT EDIT BY HAND");
        Code("using System;");
        Code("using System.Text.Json;");
        Code("using System.Text.Json.Serialization;");
        Code("using System.Drawing;");
        Code("using Mutagen.Bethesda.Skyrim;");
        Code("using Spriggan.Converters.Base;");
        Code("using Mutagen.Bethesda;");
        Code("using Microsoft.Extensions.DependencyInjection;");
        Code("");
    }


    private string GetProp()
    {
        genSym++;
        return $"prop{genSym}";
    }

    private void PrimitiveReader<T>(Type type, string getter)
    {
        if (typeof(T) == typeof(float))
        {
            Code($"{getter} = reader.GetSingle();");
        }
        else if (typeof(T) == typeof(bool))
        {
            Code($"{getter} = reader.GetBoolean();");
        }
        else
        {
            throw new NotImplementedException($"{type}");
        }
    }

    public void Write(string path)
    {
        File.WriteAllText(path, _sb.ToString());
    }

    public void Code(string c)
    {
        if (c.EndsWith("}"))
            _indent--;

        for (var i = 0; i < _indent; i++) _sb.Append("  ");
        _sb.AppendLine(c);

        if (c.EndsWith("{"))
            _indent++;
    }

    public IDisposable WithIndent()
    {
        _indent++;
        return Disposable.Create(() => _indent--);
    }

    public void EmitTypeHeader(Type tGetter, string baseName)
    {
        Code($"writer.WriteFormKeyHeader(value, options);");
    }


    private void IFormLinkNullableWriter(Type info, string getter)
    {
        Code($"if ({getter}.IsNull)");
        
        using (var _ = WithIndent()) 
            Code("writer.WriteNullValue();");

        Code("else");
        
        using (var _ = WithIndent()) 
            Code($"writer.WriteStringValue({getter}.FormKey.ModKey.Name + \":\" + {getter}.FormKey.ModKey.Type + \":\" + {getter}.FormKey.ID.ToString(\"x8\"));");

    }

    private void IFormLinkNullableReader(Type info, string getter)
    {
        Code($"if (reader.TokenType != JsonTokenType.Null)");
        using var _ = WithIndent();
        Code($"{getter}.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));");
    }
    
    private void IFormLinkWriter(Type info, string getter)
    {
        Code($"writer.WriteStringValue({getter}.FormKey.ToString());");
    }

    private void LoquiObjectWriter(Type info, string getter)
    {
        Code("writer.WriteStartObject();");
        foreach (var p in VisitorGenerator.Members(info))
        {
            Code("");
            Code($"// {p.Name}");
            Code($"writer.WritePropertyName(\"{p.Name}\");");
            EmitWriter(p.PropertyType, getter + "." + p.Name);
        }
        Code("writer.WriteEndObject();");
    }
    
    
    private void LoquiObjectReader(Type type, string getter)
    {
        Code("if (reader.TokenType != JsonTokenType.StartObject)");
        using (var _ = WithIndent())
            Code("throw new JsonException();");
        
        
        Code("while (true)");
        Code("{");
        Code("reader.Read();");
        Code("if (reader.TokenType == JsonTokenType.EndObject)");
        using (var _2 = WithIndent())
            Code("break;");

        var propName = GetProp();
        Code($"var {propName} = reader.GetString();");
        Code("reader.Read();");
        
        Code($"switch({propName})");
        Code("{");
        foreach (var prop in VisitorGenerator.Members(type))
        {
            Code($"case \"{prop.Name}\":");
            
            using var _ = WithIndent();
            EmitReader(prop.PropertyType, $"{getter}.{prop.Name}");
            Code("break;");

        }

        Code("}");
        
        Code("}");
    }


    private string CleanName(string s)
    {
        return s.Replace("+", ".");
    }
    
    private void PrimitiveWriter<T>(Type info, string getter)
    {
        if (typeof(T) == typeof(float))
        {
            Code($"writer.WriteNumberValue({getter});");
        }
        else if (typeof(T) == typeof(bool))
        {
            Code($"writer.WriteBooleanValue({getter});");
        }
        else
        {
            throw new NotImplementedException($"No writer for {info.Name}");
        }
    }

    private void EnumWriter(Type info, string getter)
    {
        if (info.CustomAttributes.Any(a => a.AttributeType == typeof(FlagsAttribute)))
            Code($"writer.WriteFlags({getter});");
        else
            Code($"writer.WriteEnum({getter});");
    }
    
    
    private void EnumReader(Type type, string getter)
    {
        if (type.CustomAttributes.Any(a => a.AttributeType == typeof(FlagsAttribute)))
            Code($"{getter} = SerializerExtensions.ReadFlags<{CleanName(type.FullName)}>(ref reader, options);");
        else
            Code($"{getter} = SerializerExtensions.ReadEnum<{CleanName(type.FullName)}>(ref reader, options);");
    }

    private void IReadOnlyListWriter(Type info, string getter)
    {
        var itype = info.GetGenericArguments()[0];
        Code("writer.WriteStartArray();");
        Code($"foreach(var itm in {getter})");
        Code("{");
        EmitWriter(itype, "itm");
        Code("}");
        Code("writer.WriteEndArray();");

    }

    private void ExtendedListReader(Type info, string getter)
    {
        var itype = info.GetGenericArguments()[0];

        Code("if (reader.TokenType != JsonTokenType.StartArray)");
        using (var _ = WithIndent())
            Code("throw new JsonException();");
        
        
        Code("while (true)");
        Code("{");
        Code("reader.Read();");
        Code("if (reader.TokenType == JsonTokenType.EndArray)");
        using (var _2 = WithIndent())
            Code("break;");
        
        if (itype.InheritsFrom(typeof(IFormLinkGetter<>)))
        {
            EmitExtendedListFormLinkGetterReadOne(info, getter);
        }
        else
        {
            throw new NotImplementedException();
        }
        
        
        Code("}");
    }

    private void EmitExtendedListFormLinkGetterReadOne(Type info, string getter)
    {
        Code($"{getter}.Add(SerializerExtensions.ReadFormKeyValue(ref reader, options));");
    }

    public void EmitWriter(Type type, string getter)
    {
        
        var (_, emitter) = _writerEmitters.FirstOrDefault(e => type.InheritsFrom(e.Key));

        
        if (emitter == null)
            throw new Exception($"No emitter for property of type {type.FullName}");
        emitter(type, getter);
    }

    public void EmitReader(Type type, string getter)
    {
        var (_, emitter) = _readerEmitters.FirstOrDefault(e => type.InheritsFrom(e.Key));
        if (emitter == null)
            throw new Exception($"No emitter for property of type {type.FullName}");
        emitter(type, getter);
    }

    public void EmitCtor(string retval, Type tMain)
    {
        if (_game == GameRelease.SkyrimLE || _game == GameRelease.SkyrimSE)
        {
            Code($"var retval = new {tMain.FullName}(SerializerExtensions.ReadFormKeyHeader(ref reader, options), SkyrimRelease.{_game});");
        }
    }
}