// THIS FILE IS AUTOGENERATED DO NOT EDIT BY HAND
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Drawing;
using Mutagen.Bethesda.Skyrim;
using Spriggan.Converters.Base;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Strings;
using Microsoft.Extensions.DependencyInjection;
using Mutagen.Bethesda.Plugins.Records;
using System.Globalization;
using Mutagen.Bethesda.Plugins;
using Noggog;

internal static class GetEventData_Reader
{
    public static Mutagen.Bethesda.Skyrim.GetEventData ReadInner(ref Utf8JsonReader reader, JsonSerializerOptions options)
    {
        Mutagen.Bethesda.Skyrim.GetEventData cls = new();
        while (true)
        {
            reader.Read();
            if (reader.TokenType == JsonTokenType.EndObject)
                break;
            var prop1 = reader.GetString();
            reader.Read();
            switch(prop1)
            {
                case "EventFunction":
                    cls.EventFunction = reader.GetUInt16();
                    break;
                case "EventMember":
                    cls.EventMember = reader.GetUInt16();
                    break;
                case "Parameter3":
                    cls.Parameter3.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "RunOnType":
                    cls.RunOnType = SerializerExtensions.ReadEnum<Mutagen.Bethesda.Skyrim.Condition.RunOnType>(ref reader, options);
                    break;
                case "Reference":
                    cls.Reference.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "Unknown3":
                    cls.Unknown3 = reader.GetInt32();
                    break;
            }
        }
        return cls;
    }
}
