// THIS FILE IS AUTOGENERATED DO NOT EDIT BY HAND
using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Drawing;
using Mutagen.Bethesda.Skyrim;
using Spriggan.Converters.Base;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Strings;
using Microsoft.Extensions.DependencyInjection;
using Mutagen.Bethesda.Plugins.Records;
using System.Globalization;
using Mutagen.Bethesda.Plugins;
using Noggog;

internal static class PlacedNpc_Reader
{
    public static Mutagen.Bethesda.Skyrim.PlacedNpc ReadInner(ref Utf8JsonReader reader, FormKey formKey, JsonSerializerOptions options)
    {
        var cls = new Mutagen.Bethesda.Skyrim.PlacedNpc(formKey, SkyrimRelease.SkyrimSE);
        while (true)
        {
            reader.Read();
            if (reader.TokenType == JsonTokenType.EndObject)
                break;
            var prop1 = reader.GetString();
            reader.Read();
            switch(prop1)
            {
                case "VirtualMachineAdapter":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;
                            var prop2 = reader.GetString();
                            reader.Read();
                            switch(prop2)
                            {
                                case "Version":
                                    cls.VirtualMachineAdapter.Version = reader.GetInt16();
                                    break;
                                case "ObjectFormat":
                                    cls.VirtualMachineAdapter.ObjectFormat = reader.GetUInt16();
                                    break;
                                case "Scripts":
                                    if (reader.TokenType != JsonTokenType.Null)
                                    {
                                        if (reader.TokenType != JsonTokenType.StartArray)
                                            throw new JsonException();
                                        while (true)
                                        {
                                            reader.Read();
                                            if (reader.TokenType == JsonTokenType.EndArray)
                                                break;
                                            Mutagen.Bethesda.Skyrim.ScriptEntry itm3 = new Mutagen.Bethesda.Skyrim.ScriptEntry();
                                            if (reader.TokenType != JsonTokenType.Null)
                                            {
                                                if (reader.TokenType != JsonTokenType.StartObject)
                                                    throw new JsonException();
                                                while (true)
                                                {
                                                    reader.Read();
                                                    if (reader.TokenType == JsonTokenType.EndObject)
                                                        break;
                                                    var prop4 = reader.GetString();
                                                    reader.Read();
                                                    switch(prop4)
                                                    {
                                                        case "Name":
                                                            itm3.Name = reader.GetString();
                                                            break;
                                                        case "Flags":
                                                            itm3.Flags = SerializerExtensions.ReadEnum<Mutagen.Bethesda.Skyrim.ScriptEntry.Flag>(ref reader, options);
                                                            break;
                                                        case "Properties":
                                                            if (reader.TokenType != JsonTokenType.Null)
                                                            {
                                                                if (reader.TokenType != JsonTokenType.StartArray)
                                                                    throw new JsonException();
                                                                while (true)
                                                                {
                                                                    reader.Read();
                                                                    if (reader.TokenType == JsonTokenType.EndArray)
                                                                        break;
                                                                    ScriptProperty itm5 = default;
                                                                    itm5 = ScriptProperty_Reader.ReadOuter(ref reader, options);
                                                                    itm3.Properties.Add(itm5);
                                                                }
                                                            }
                                                            break;
                                                    }
                                                }
                                            }
                                            else
                                            {
                                                reader.Skip();
                                            }
                                            cls.VirtualMachineAdapter.Scripts.Add(itm3);
                                        }
                                    }
                                    break;
                            }
                        }
                    }
                    else
                    {
                        reader.Skip();
                    }
                    break;
                case "Base":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.Base.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "EncounterZone":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.EncounterZone.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "RagdollData":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.RagdollData = reader.GetBytesFromBase64();
                    }
                    break;
                case "RagdollBipedData":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.RagdollBipedData = reader.GetBytesFromBase64();
                    }
                    break;
                case "Patrol":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;
                            var prop6 = reader.GetString();
                            reader.Read();
                            switch(prop6)
                            {
                                case "IdleTime":
                                    cls.Patrol.IdleTime = reader.GetSingle();
                                    break;
                                case "Idle":
                                    cls.Patrol.Idle.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                                    break;
                                case "SCHR":
                                    if (reader.TokenType != JsonTokenType.Null)
                                    {
                                        cls.Patrol.SCHR = reader.GetBytesFromBase64();
                                    }
                                    break;
                                case "SCTX":
                                    if (reader.TokenType != JsonTokenType.Null)
                                    {
                                        cls.Patrol.SCTX = reader.GetBytesFromBase64();
                                    }
                                    break;
                                case "Topics":
                                    if (reader.TokenType != JsonTokenType.Null)
                                    {
                                        if (reader.TokenType != JsonTokenType.StartArray)
                                            throw new JsonException();
                                        while (true)
                                        {
                                            reader.Read();
                                            if (reader.TokenType == JsonTokenType.EndArray)
                                                break;
                                            ATopicReference itm7 = default;
                                            itm7 = ATopicReference_Reader.ReadOuter(ref reader, options);
                                            cls.Patrol.Topics.Add(itm7);
                                        }
                                    }
                                    break;
                            }
                        }
                    }
                    else
                    {
                        reader.Skip();
                    }
                    break;
                case "LevelModifier":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.LevelModifier = SerializerExtensions.ReadEnum<Mutagen.Bethesda.Skyrim.Level>(ref reader, options);
                    }
                    break;
                case "MerchantContainer":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.MerchantContainer.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "Count":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.Count = reader.GetInt32();
                    }
                    break;
                case "Radius":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.Radius = reader.GetSingle();
                    }
                    break;
                case "Health":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.Health = reader.GetSingle();
                    }
                    break;
                case "LinkedReferences":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartArray)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndArray)
                                break;
                            Mutagen.Bethesda.Skyrim.LinkedReferences itm8 = new Mutagen.Bethesda.Skyrim.LinkedReferences();
                            if (reader.TokenType != JsonTokenType.Null)
                            {
                                if (reader.TokenType != JsonTokenType.StartObject)
                                    throw new JsonException();
                                while (true)
                                {
                                    reader.Read();
                                    if (reader.TokenType == JsonTokenType.EndObject)
                                        break;
                                    var prop9 = reader.GetString();
                                    reader.Read();
                                    switch(prop9)
                                    {
                                        case "Versioning":
                                            itm8.Versioning = SerializerExtensions.ReadFlags<Mutagen.Bethesda.Skyrim.LinkedReferences.VersioningBreaks>(ref reader, options);
                                            break;
                                        case "KeywordOrReference":
                                            itm8.KeywordOrReference.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                                            break;
                                        case "Reference":
                                            itm8.Reference.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                                            break;
                                    }
                                }
                            }
                            else
                            {
                                reader.Skip();
                            }
                            cls.LinkedReferences.Add(itm8);
                        }
                    }
                    break;
                case "ActivateParents":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;
                            var prop10 = reader.GetString();
                            reader.Read();
                            switch(prop10)
                            {
                                case "Flags":
                                    cls.ActivateParents.Flags = SerializerExtensions.ReadFlags<Mutagen.Bethesda.Skyrim.ActivateParents.Flag>(ref reader, options);
                                    break;
                                case "Parents":
                                    if (reader.TokenType != JsonTokenType.Null)
                                    {
                                        if (reader.TokenType != JsonTokenType.StartArray)
                                            throw new JsonException();
                                        while (true)
                                        {
                                            reader.Read();
                                            if (reader.TokenType == JsonTokenType.EndArray)
                                                break;
                                            Mutagen.Bethesda.Skyrim.ActivateParent itm11 = new Mutagen.Bethesda.Skyrim.ActivateParent();
                                            if (reader.TokenType != JsonTokenType.Null)
                                            {
                                                if (reader.TokenType != JsonTokenType.StartObject)
                                                    throw new JsonException();
                                                while (true)
                                                {
                                                    reader.Read();
                                                    if (reader.TokenType == JsonTokenType.EndObject)
                                                        break;
                                                    var prop12 = reader.GetString();
                                                    reader.Read();
                                                    switch(prop12)
                                                    {
                                                        case "Reference":
                                                            itm11.Reference.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                                                            break;
                                                        case "Delay":
                                                            itm11.Delay = reader.GetSingle();
                                                            break;
                                                    }
                                                }
                                            }
                                            else
                                            {
                                                reader.Skip();
                                            }
                                            cls.ActivateParents.Parents.Add(itm11);
                                        }
                                    }
                                    break;
                            }
                        }
                    }
                    else
                    {
                        reader.Skip();
                    }
                    break;
                case "LinkedReferenceColor":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;
                            var prop13 = reader.GetString();
                            reader.Read();
                            switch(prop13)
                            {
                                case "Start":
                                    cls.LinkedReferenceColor.Start = Color.FromArgb(int.Parse(reader.GetString(), NumberStyles.HexNumber));
                                    break;
                                case "End":
                                    cls.LinkedReferenceColor.End = Color.FromArgb(int.Parse(reader.GetString(), NumberStyles.HexNumber));
                                    break;
                            }
                        }
                    }
                    else
                    {
                        reader.Skip();
                    }
                    break;
                case "PersistentLocation":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.PersistentLocation.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "LocationReference":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.LocationReference.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "IsIgnoredBySandbox":
                    cls.IsIgnoredBySandbox = reader.GetBoolean();
                    break;
                case "LocationRefTypes":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.LocationRefTypes ??= new();
                        if (reader.TokenType != JsonTokenType.StartArray)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndArray)
                                break;
                            cls.LocationRefTypes.Add(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                        }
                    }
                    break;
                case "HeadTrackingWeight":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.HeadTrackingWeight = reader.GetSingle();
                    }
                    break;
                case "Horse":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.Horse.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "FavorCost":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.FavorCost = reader.GetSingle();
                    }
                    break;
                case "EnableParent":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;
                            var prop14 = reader.GetString();
                            reader.Read();
                            switch(prop14)
                            {
                                case "Versioning":
                                    cls.EnableParent.Versioning = SerializerExtensions.ReadFlags<Mutagen.Bethesda.Skyrim.EnableParent.VersioningBreaks>(ref reader, options);
                                    break;
                                case "Reference":
                                    cls.EnableParent.Reference.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                                    break;
                                case "Flags":
                                    cls.EnableParent.Flags = SerializerExtensions.ReadFlags<Mutagen.Bethesda.Skyrim.EnableParent.Flag>(ref reader, options);
                                    break;
                                case "Unknown":
                                    cls.EnableParent.Unknown = reader.GetBytesFromBase64();
                                    break;
                            }
                        }
                    }
                    else
                    {
                        reader.Skip();
                    }
                    break;
                case "Ownership":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;
                            var prop15 = reader.GetString();
                            reader.Read();
                            switch(prop15)
                            {
                                case "Owner":
                                    if (reader.TokenType != JsonTokenType.Null)
                                        cls.Ownership.Owner.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                                    break;
                                case "FactionRank":
                                    if (reader.TokenType != JsonTokenType.Null)
                                    {
                                        cls.Ownership.FactionRank = reader.GetInt32();
                                    }
                                    break;
                            }
                        }
                    }
                    else
                    {
                        reader.Skip();
                    }
                    break;
                case "Emittance":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.Emittance.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "MultiboundReference":
                    if (reader.TokenType != JsonTokenType.Null)
                        cls.MultiboundReference.SetTo(SerializerExtensions.ReadFormKeyValue(ref reader, options));
                    break;
                case "IsIgnoredBySandbox2":
                    cls.IsIgnoredBySandbox2 = reader.GetBoolean();
                    break;
                case "Scale":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        cls.Scale = reader.GetSingle();
                    }
                    break;
                case "Placement":
                    if (reader.TokenType != JsonTokenType.Null)
                    {
                        if (reader.TokenType != JsonTokenType.StartObject)
                            throw new JsonException();
                        while (true)
                        {
                            reader.Read();
                            if (reader.TokenType == JsonTokenType.EndObject)
                                break;
                            var prop16 = reader.GetString();
                            reader.Read();
                            switch(prop16)
                            {
                                case "Position":
                                    cls.Placement.Position = SerializerExtensions.ReadP3Float(ref reader, options);
                                    break;
                                case "Rotation":
                                    cls.Placement.Rotation = SerializerExtensions.ReadP3Float(ref reader, options);
                                    break;
                            }
                        }
                    }
                    else
                    {
                        reader.Skip();
                    }
                    break;
                case "MajorFlags":
                    cls.MajorFlags = SerializerExtensions.ReadFlags<Mutagen.Bethesda.Skyrim.PlacedNpc.MajorFlag>(ref reader, options);
                    break;
            }
        }
        return cls;
    }
}
